[package]
name = "youtube_audio_feed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
atom_syndication = "0.11.0"
axum = { version = "0.5.15", features = ["macros", "headers"] }
http-types = "2.12.0"
once_cell = "1.13.1"
regex = "1.6.0"
reqwest = { version = "0.11.11", default_features = false, features = ["rustls-tls", "stream"] }
rss = "2.0.1"
serde = { version = "1.0.143", features = ["derive"] }
# simd requires rustc nightly
# tl = { version = "0.7.6", features = ["simd"] }
tl = { version = "0.7.6" }
tokio = { version = "1.20.1", features = ["macros"] }
