[package]
name = "youtube_audio_feed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
async-std = { version = "1.12.0", features = ["attributes"] }
atom_syndication = "0.11.0"
axum = { version = "0.5.15", features = ["macros"] }
http-types = "2.12.0"
reqwest = "0.11.11"
rss = "2.0.1"
