# fly.toml app configuration file generated for youtube-audio-feed on 2023-08-20T15:08:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "youtube-audio-feed"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"
swap_size_mb = 512

[experimental]
  auto_rollback = true

[build]
  image = "registry.fly.io/youtube-audio-feed:latest"

[mounts]
  source = "youtube_audio_feed_stash"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  auto_stop_machines = false

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.http_checks]]
    interval = "5s"
    timeout = "5s"
    grace_period = "1s"
    method = "get"
    path = "/health"
    protocol = "http"

  # [[services.http_checks]]
  #   interval = "5m0s"
  #   timeout = "1m0s"
  #   grace_period = "10s"
  #   method = "get"
  #   path = "/channel/UC1yNl2E66ZzKApQdRuTQ4tw"
  #   protocol = "http"
